#include QMK_KEYBOARD_H
// #include <stdio.h>
#include "leds.c"

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT( // Basic
			KC_ESC  , KC_Q    , KC_W    , KC_E    , KC_R    , KC_T    ,/**/KC_Y    , KC_U    , KC_I    , KC_O    , KC_P    , KC_BSPC ,
			KC_TAB  , KC_A    , KC_S    , KC_D    , KC_F    , KC_G    ,/**/KC_H    , KC_J    , KC_K    , KC_L    , KC_SCLN , KC_QUOT ,
			KC_LSFT , KC_Z    , KC_X    , KC_C    , KC_V    , KC_B    ,/**/KC_N    , KC_M    , KC_COMM , KC_DOT  , KC_SLSH , KC_RSFT ,
			KC_LCTL , KC_LGUI , KC_LALT , KC_LCTL , OSL(1)  , KC_SPC  ,/**/KC_ENT  , OSL(2)  , KC_LEFT , KC_DOWN , KC_UP   , KC_RGHT ),

	[1] = LAYOUT( // fn
			QK_BOOT , A(KC_F4), KC_TAB  ,S(KC_TAB), KC_F2   , KC_WREF ,/**/KC_VOLU , KC_F9   , KC_F10  , KC_F11  , KC_F12  , KC_BRIU ,
			KC_CALC , OS_LALT , OS_LSFT , KC_DEL  , OS_LCTL , OS_LGUI ,/**/KC_VOLD , KC_F1   , KC_F2   , KC_F3   , KC_F4   , KC_BRID ,
			KC_MYCM , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , KC_WHOM ,/**/KC_MUTE , KC_F5   , KC_F6   , KC_F7   , KC_F8   , XXXXXXX ,
			KC_PSCR , KC_SCRL , KC_PAUS , KC_INS  , _______ , TO(3)   ,/**/KC_APP  ,G(KC_SPC), KC_HOME , KC_PGDN , KC_PGUP , KC_END  ),

	[2] = LAYOUT( // Punctuation
			KC_GRV  , KC_1    , KC_2    , KC_3    , KC_4    , KC_5    ,/**/KC_6    , KC_7    , KC_8    , KC_9    , KC_0    , QK_BOOT ,
			KC_TILD , KC_ASTR , KC_LCBR , KC_LPRN , KC_MINS , KC_LBRC ,/**/KC_RBRC , KC_EQL  , KC_RPRN , KC_RCBR , KC_PLUS , KC_PIPE ,
			KC_UNDS , KC_EXLM , KC_AT   , KC_HASH , KC_DLR  , KC_PERC ,/**/KC_CIRC , KC_AMPR , XXXXXXX , XXXXXXX , KC_BSLS , XXXXXXX ,
			UG_VALD , UG_VALU , UG_TOGG , UG_HUEU , KC_CAPS , UG_NEXT ,/**/OS_TOGG , _______ , KC_APP  , KC_RALT , KC_RGUI , KC_RCTL ),

	[3] = LAYOUT( // Keypad
			TO(0)   , KC_PAST , KC_P7   , KC_P8   , KC_P9   , KC_PMNS ,/**/KC_PAST , KC_P7   , KC_P8   , KC_P9   , KC_PMNS , TO(0)   ,
			KC_BSPC , KC_PSLS , KC_P4   , KC_P5   , KC_P6   , KC_PPLS ,/**/KC_PSLS , KC_P4   , KC_P5   , KC_P6   , KC_PPLS , KC_BSPC ,
			KC_DEL  , KC_LPRN , KC_P1   , KC_P2   , KC_P3   , KC_RPRN ,/**/KC_LPRN , KC_P1   , KC_P2   , KC_P3   , KC_RPRN , KC_DEL  ,
			KC_NUM  , KC_LALT , KC_P0   , KC_P0   , KC_PDOT , KC_PENT ,/**/KC_LALT , KC_P0   , KC_P0   , KC_PDOT , KC_PENT , KC_NUM  ),

	[4] = LAYOUT(
			XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ,/**/XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ,
			XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ,/**/XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ,
			XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ,/**/XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ,
			XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ,/**/XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ),

	[5] = LAYOUT(
			XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ,/**/XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ,
			XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ,/**/XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ,
			XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ,/**/XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ,
			XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ,/**/XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ),

	[6] = LAYOUT(
			XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ,/**/XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ,
			XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ,/**/XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ,
			XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ,/**/XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ,
			XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ,/**/XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ),

	[7] = LAYOUT(
			XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ,/**/XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ,
			XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ,/**/XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ,
			XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ,/**/XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ,
			XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ,/**/XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ),

	[8] = LAYOUT(
			XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ,/**/XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ,
			XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ,/**/XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ,
			XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ,/**/XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ,
			XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ,/**/XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX , XXXXXXX ),
};
